apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGO_HOST: localhost
  MONGO_PORT: "27017"
  MONGO_USERNAME: myuser
  MONGO_PASSWORD: mypassword
  MONGO_DATABASE: myappdb
